name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: WordAI.VSTO
      run: dotnet restore WordAI.VSTO.csproj

    - name: Build
      working-directory: WordAI.VSTO
      run: dotnet build WordAI.VSTO.csproj --no-restore

    - name: Test
      working-directory: WordAI.VSTO
      run: dotnet test WordAI.VSTO.csproj --no-build --verbosity normal
